name: release

on:
  push:
    branches:
      - main
      - v*
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.2'
      - name: Prepare
        id: prepare
        run: |
          VERSION=v1.0
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=ref::docker.io/rosvik/oci-distribution-conformance-tests:${VERSION}
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build
        run: |
          docker build \
            --build-arg VERSION=${{ steps.prepare.outputs.version }} \
            -t ${{ steps.prepare.outputs.ref }} \
            conformance/
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: conformance/
          push: true
          tags: ${{ steps.prepare.outputs.ref }}
          build-args: |
            VERSION=${{ steps.prepare.outputs.version }}
